/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 4.8.4-2ubuntu1~14.04.3 -O2 -fstack-protector -fPIC -Os) */

(* top =  1  *)
(* src = "Estructural.v:1" *)
module Estructural(clk, select, data_in0, data_in1, data_in2, data_in3, pop0, pop1, pop2, pop3, reset_L, request, contador, valid);
  (* src = "Estructural.v:25" *)
  wire [2:0] _000_;
  (* src = "Estructural.v:25" *)
  wire [2:0] _001_;
  (* src = "Estructural.v:25" *)
  wire [2:0] _002_;
  (* src = "Estructural.v:25" *)
  wire [2:0] _003_;
  (* src = "Estructural.v:25" *)
  wire [2:0] _004_;
  (* src = "Estructural.v:25" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  (* src = "Estructural.v:2" *)
  input clk;
  (* src = "Estructural.v:14" *)
  output [2:0] contador;
  (* src = "Estructural.v:22" *)
  wire [2:0] contador0;
  (* src = "Estructural.v:22" *)
  wire [2:0] contador1;
  (* src = "Estructural.v:22" *)
  wire [2:0] contador2;
  (* src = "Estructural.v:22" *)
  wire [2:0] contador3;
  (* src = "Estructural.v:4" *)
  input [9:0] data_in0;
  (* src = "Estructural.v:5" *)
  input [9:0] data_in1;
  (* src = "Estructural.v:6" *)
  input [9:0] data_in2;
  (* src = "Estructural.v:7" *)
  input [9:0] data_in3;
  (* src = "Estructural.v:8" *)
  input pop0;
  (* src = "Estructural.v:9" *)
  input pop1;
  (* src = "Estructural.v:10" *)
  input pop2;
  (* src = "Estructural.v:11" *)
  input pop3;
  (* src = "Estructural.v:13" *)
  input request;
  (* src = "Estructural.v:12" *)
  input reset_L;
  (* src = "Estructural.v:3" *)
  input [1:0] select;
  (* src = "Estructural.v:15" *)
  output valid;
  NAND _087_ (
    .A(pop3),
    .B(contador3[0]),
    .Y(_038_)
  );
  NOT _088_ (
    .A(_038_),
    .Y(_039_)
  );
  NOT _089_ (
    .A(contador3[0]),
    .Y(_040_)
  );
  NOT _090_ (
    .A(pop3),
    .Y(_041_)
  );
  NAND _091_ (
    .A(_041_),
    .B(_040_),
    .Y(_042_)
  );
  NAND _092_ (
    .A(_042_),
    .B(reset_L),
    .Y(_043_)
  );
  NOR _093_ (
    .A(_043_),
    .B(_039_),
    .Y(_003_[0])
  );
  NOT _094_ (
    .A(contador3[1]),
    .Y(_044_)
  );
  NOR _095_ (
    .A(_038_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _096_ (
    .A(_038_),
    .B(_044_),
    .Y(_046_)
  );
  NAND _097_ (
    .A(_046_),
    .B(reset_L),
    .Y(_047_)
  );
  NOR _098_ (
    .A(_047_),
    .B(_045_),
    .Y(_003_[1])
  );
  NOR _099_ (
    .A(_045_),
    .B(contador3[2]),
    .Y(_048_)
  );
  NAND _100_ (
    .A(_045_),
    .B(contador3[2]),
    .Y(_049_)
  );
  NAND _101_ (
    .A(_049_),
    .B(reset_L),
    .Y(_050_)
  );
  NOR _102_ (
    .A(_050_),
    .B(_048_),
    .Y(_003_[2])
  );
  NAND _103_ (
    .A(pop2),
    .B(contador2[0]),
    .Y(_051_)
  );
  NOT _104_ (
    .A(_051_),
    .Y(_052_)
  );
  NOT _105_ (
    .A(contador2[0]),
    .Y(_053_)
  );
  NOT _106_ (
    .A(pop2),
    .Y(_054_)
  );
  NAND _107_ (
    .A(_054_),
    .B(_053_),
    .Y(_055_)
  );
  NAND _108_ (
    .A(_055_),
    .B(reset_L),
    .Y(_056_)
  );
  NOR _109_ (
    .A(_056_),
    .B(_052_),
    .Y(_002_[0])
  );
  NOT _110_ (
    .A(contador2[1]),
    .Y(_057_)
  );
  NOR _111_ (
    .A(_051_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _112_ (
    .A(_051_),
    .B(_057_),
    .Y(_059_)
  );
  NAND _113_ (
    .A(_059_),
    .B(reset_L),
    .Y(_060_)
  );
  NOR _114_ (
    .A(_060_),
    .B(_058_),
    .Y(_002_[1])
  );
  NOR _115_ (
    .A(_058_),
    .B(contador2[2]),
    .Y(_061_)
  );
  NAND _116_ (
    .A(_058_),
    .B(contador2[2]),
    .Y(_062_)
  );
  NAND _117_ (
    .A(_062_),
    .B(reset_L),
    .Y(_063_)
  );
  NOR _118_ (
    .A(_063_),
    .B(_061_),
    .Y(_002_[2])
  );
  NAND _119_ (
    .A(pop1),
    .B(contador1[0]),
    .Y(_064_)
  );
  NOT _120_ (
    .A(_064_),
    .Y(_065_)
  );
  NOT _121_ (
    .A(contador1[0]),
    .Y(_066_)
  );
  NOT _122_ (
    .A(pop1),
    .Y(_067_)
  );
  NAND _123_ (
    .A(_067_),
    .B(_066_),
    .Y(_068_)
  );
  NAND _124_ (
    .A(_068_),
    .B(reset_L),
    .Y(_069_)
  );
  NOR _125_ (
    .A(_069_),
    .B(_065_),
    .Y(_001_[0])
  );
  NOT _126_ (
    .A(contador1[1]),
    .Y(_070_)
  );
  NOR _127_ (
    .A(_064_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _128_ (
    .A(_064_),
    .B(_070_),
    .Y(_072_)
  );
  NAND _129_ (
    .A(_072_),
    .B(reset_L),
    .Y(_073_)
  );
  NOR _130_ (
    .A(_073_),
    .B(_071_),
    .Y(_001_[1])
  );
  NOR _131_ (
    .A(_071_),
    .B(contador1[2]),
    .Y(_074_)
  );
  NAND _132_ (
    .A(_071_),
    .B(contador1[2]),
    .Y(_075_)
  );
  NAND _133_ (
    .A(_075_),
    .B(reset_L),
    .Y(_076_)
  );
  NOR _134_ (
    .A(_076_),
    .B(_074_),
    .Y(_001_[2])
  );
  NAND _135_ (
    .A(pop0),
    .B(contador0[0]),
    .Y(_077_)
  );
  NOT _136_ (
    .A(_077_),
    .Y(_078_)
  );
  NOT _137_ (
    .A(contador0[0]),
    .Y(_079_)
  );
  NOT _138_ (
    .A(pop0),
    .Y(_080_)
  );
  NAND _139_ (
    .A(_080_),
    .B(_079_),
    .Y(_081_)
  );
  NAND _140_ (
    .A(_081_),
    .B(reset_L),
    .Y(_082_)
  );
  NOR _141_ (
    .A(_082_),
    .B(_078_),
    .Y(_000_[0])
  );
  NOT _142_ (
    .A(contador0[1]),
    .Y(_083_)
  );
  NOR _143_ (
    .A(_077_),
    .B(_083_),
    .Y(_084_)
  );
  NAND _144_ (
    .A(_077_),
    .B(_083_),
    .Y(_085_)
  );
  NAND _145_ (
    .A(_085_),
    .B(reset_L),
    .Y(_086_)
  );
  NOR _146_ (
    .A(_086_),
    .B(_084_),
    .Y(_000_[1])
  );
  NOR _147_ (
    .A(_084_),
    .B(contador0[2]),
    .Y(_006_)
  );
  NAND _148_ (
    .A(_084_),
    .B(contador0[2]),
    .Y(_007_)
  );
  NAND _149_ (
    .A(_007_),
    .B(reset_L),
    .Y(_008_)
  );
  NOR _150_ (
    .A(_008_),
    .B(_006_),
    .Y(_000_[2])
  );
  NOT _151_ (
    .A(reset_L),
    .Y(_009_)
  );
  NOT _152_ (
    .A(request),
    .Y(_010_)
  );
  NOR _153_ (
    .A(_010_),
    .B(_009_),
    .Y(_005_)
  );
  NOR _154_ (
    .A(select[1]),
    .B(select[0]),
    .Y(_011_)
  );
  NAND _155_ (
    .A(_011_),
    .B(contador0[0]),
    .Y(_012_)
  );
  NOT _156_ (
    .A(select[0]),
    .Y(_013_)
  );
  NOT _157_ (
    .A(select[1]),
    .Y(_014_)
  );
  NOR _158_ (
    .A(_014_),
    .B(_013_),
    .Y(_015_)
  );
  NAND _159_ (
    .A(_015_),
    .B(contador3[0]),
    .Y(_016_)
  );
  NAND _160_ (
    .A(_016_),
    .B(_012_),
    .Y(_017_)
  );
  NOR _161_ (
    .A(select[1]),
    .B(_013_),
    .Y(_018_)
  );
  NAND _162_ (
    .A(_018_),
    .B(contador1[0]),
    .Y(_019_)
  );
  NOR _163_ (
    .A(_014_),
    .B(select[0]),
    .Y(_020_)
  );
  NAND _164_ (
    .A(_020_),
    .B(contador2[0]),
    .Y(_021_)
  );
  NAND _165_ (
    .A(_021_),
    .B(_019_),
    .Y(_022_)
  );
  NOR _166_ (
    .A(_022_),
    .B(_017_),
    .Y(_023_)
  );
  NOR _167_ (
    .A(_023_),
    .B(_009_),
    .Y(_004_[0])
  );
  NAND _168_ (
    .A(_011_),
    .B(contador0[1]),
    .Y(_024_)
  );
  NAND _169_ (
    .A(_015_),
    .B(contador3[1]),
    .Y(_025_)
  );
  NAND _170_ (
    .A(_025_),
    .B(_024_),
    .Y(_026_)
  );
  NAND _171_ (
    .A(_018_),
    .B(contador1[1]),
    .Y(_027_)
  );
  NAND _172_ (
    .A(_020_),
    .B(contador2[1]),
    .Y(_028_)
  );
  NAND _173_ (
    .A(_028_),
    .B(_027_),
    .Y(_029_)
  );
  NOR _174_ (
    .A(_029_),
    .B(_026_),
    .Y(_030_)
  );
  NOR _175_ (
    .A(_030_),
    .B(_009_),
    .Y(_004_[1])
  );
  NAND _176_ (
    .A(_011_),
    .B(contador0[2]),
    .Y(_031_)
  );
  NAND _177_ (
    .A(_015_),
    .B(contador3[2]),
    .Y(_032_)
  );
  NAND _178_ (
    .A(_032_),
    .B(_031_),
    .Y(_033_)
  );
  NAND _179_ (
    .A(_018_),
    .B(contador1[2]),
    .Y(_034_)
  );
  NAND _180_ (
    .A(_020_),
    .B(contador2[2]),
    .Y(_035_)
  );
  NAND _181_ (
    .A(_035_),
    .B(_034_),
    .Y(_036_)
  );
  NOR _182_ (
    .A(_036_),
    .B(_033_),
    .Y(_037_)
  );
  NOR _183_ (
    .A(_037_),
    .B(_009_),
    .Y(_004_[2])
  );
  DFF _184_ (
    .C(clk),
    .D(_004_[0]),
    .Q(contador[0])
  );
  DFF _185_ (
    .C(clk),
    .D(_004_[1]),
    .Q(contador[1])
  );
  DFF _186_ (
    .C(clk),
    .D(_004_[2]),
    .Q(contador[2])
  );
  DFF _187_ (
    .C(clk),
    .D(_005_),
    .Q(valid)
  );
  DFF _188_ (
    .C(clk),
    .D(_000_[0]),
    .Q(contador0[0])
  );
  DFF _189_ (
    .C(clk),
    .D(_000_[1]),
    .Q(contador0[1])
  );
  DFF _190_ (
    .C(clk),
    .D(_000_[2]),
    .Q(contador0[2])
  );
  DFF _191_ (
    .C(clk),
    .D(_001_[0]),
    .Q(contador1[0])
  );
  DFF _192_ (
    .C(clk),
    .D(_001_[1]),
    .Q(contador1[1])
  );
  DFF _193_ (
    .C(clk),
    .D(_001_[2]),
    .Q(contador1[2])
  );
  DFF _194_ (
    .C(clk),
    .D(_002_[0]),
    .Q(contador2[0])
  );
  DFF _195_ (
    .C(clk),
    .D(_002_[1]),
    .Q(contador2[1])
  );
  DFF _196_ (
    .C(clk),
    .D(_002_[2]),
    .Q(contador2[2])
  );
  DFF _197_ (
    .C(clk),
    .D(_003_[0]),
    .Q(contador3[0])
  );
  DFF _198_ (
    .C(clk),
    .D(_003_[1]),
    .Q(contador3[1])
  );
  DFF _199_ (
    .C(clk),
    .D(_003_[2]),
    .Q(contador3[2])
  );
endmodule
