/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 4.8.4-2ubuntu1~14.04.3 -O2 -fstack-protector -fPIC -Os) */

(* top =  1  *)
(* src = "byte_strippingS.v:1" *)
module byte_strippingS(data_in, valid, reset_L, clock1, clock2, clock4, lane_0, lane_1, valid0, valid1);
  (* src = "byte_strippingS.v:9" *)
  wire [31:0] _000_;
  (* src = "byte_strippingS.v:9" *)
  wire [31:0] _001_;
  (* src = "byte_strippingS.v:9" *)
  wire _002_;
  (* src = "byte_strippingS.v:9" *)
  wire _003_;
  (* src = "byte_strippingS.v:9" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  (* src = "byte_strippingS.v:3" *)
  input clock1;
  (* src = "byte_strippingS.v:3" *)
  input clock2;
  (* src = "byte_strippingS.v:3" *)
  input clock4;
  (* src = "byte_strippingS.v:2" *)
  input [31:0] data_in;
  (* src = "byte_strippingS.v:4" *)
  output [31:0] lane_0;
  (* src = "byte_strippingS.v:4" *)
  output [31:0] lane_1;
  (* src = "byte_strippingS.v:3" *)
  input reset_L;
  (* src = "byte_strippingS.v:7" *)
  wire selector;
  (* src = "byte_strippingS.v:3" *)
  input valid;
  (* src = "byte_strippingS.v:5" *)
  output valid0;
  (* src = "byte_strippingS.v:5" *)
  output valid1;
  NOT _204_ (
    .A(reset_L),
    .Y(_005_)
  );
  NAND _205_ (
    .A(selector),
    .B(data_in[0]),
    .Y(_072_)
  );
  NOT _206_ (
    .A(selector),
    .Y(_002_)
  );
  NAND _207_ (
    .A(_002_),
    .B(lane_0[0]),
    .Y(_073_)
  );
  NAND _208_ (
    .A(_073_),
    .B(_072_),
    .Y(_000_[0])
  );
  NAND _209_ (
    .A(data_in[1]),
    .B(selector),
    .Y(_074_)
  );
  NAND _210_ (
    .A(lane_0[1]),
    .B(_002_),
    .Y(_075_)
  );
  NAND _211_ (
    .A(_075_),
    .B(_074_),
    .Y(_000_[1])
  );
  NAND _212_ (
    .A(data_in[2]),
    .B(selector),
    .Y(_076_)
  );
  NAND _213_ (
    .A(lane_0[2]),
    .B(_002_),
    .Y(_077_)
  );
  NAND _214_ (
    .A(_077_),
    .B(_076_),
    .Y(_000_[2])
  );
  NAND _215_ (
    .A(data_in[3]),
    .B(selector),
    .Y(_078_)
  );
  NAND _216_ (
    .A(lane_0[3]),
    .B(_002_),
    .Y(_079_)
  );
  NAND _217_ (
    .A(_079_),
    .B(_078_),
    .Y(_000_[3])
  );
  NAND _218_ (
    .A(data_in[4]),
    .B(selector),
    .Y(_080_)
  );
  NAND _219_ (
    .A(lane_0[4]),
    .B(_002_),
    .Y(_081_)
  );
  NAND _220_ (
    .A(_081_),
    .B(_080_),
    .Y(_000_[4])
  );
  NAND _221_ (
    .A(data_in[5]),
    .B(selector),
    .Y(_082_)
  );
  NAND _222_ (
    .A(lane_0[5]),
    .B(_002_),
    .Y(_083_)
  );
  NAND _223_ (
    .A(_083_),
    .B(_082_),
    .Y(_000_[5])
  );
  NAND _224_ (
    .A(data_in[6]),
    .B(selector),
    .Y(_084_)
  );
  NAND _225_ (
    .A(lane_0[6]),
    .B(_002_),
    .Y(_085_)
  );
  NAND _226_ (
    .A(_085_),
    .B(_084_),
    .Y(_000_[6])
  );
  NAND _227_ (
    .A(data_in[7]),
    .B(selector),
    .Y(_086_)
  );
  NAND _228_ (
    .A(lane_0[7]),
    .B(_002_),
    .Y(_087_)
  );
  NAND _229_ (
    .A(_087_),
    .B(_086_),
    .Y(_000_[7])
  );
  NAND _230_ (
    .A(data_in[8]),
    .B(selector),
    .Y(_088_)
  );
  NAND _231_ (
    .A(lane_0[8]),
    .B(_002_),
    .Y(_089_)
  );
  NAND _232_ (
    .A(_089_),
    .B(_088_),
    .Y(_000_[8])
  );
  NAND _233_ (
    .A(data_in[9]),
    .B(selector),
    .Y(_090_)
  );
  NAND _234_ (
    .A(lane_0[9]),
    .B(_002_),
    .Y(_091_)
  );
  NAND _235_ (
    .A(_091_),
    .B(_090_),
    .Y(_000_[9])
  );
  NAND _236_ (
    .A(data_in[10]),
    .B(selector),
    .Y(_092_)
  );
  NAND _237_ (
    .A(lane_0[10]),
    .B(_002_),
    .Y(_093_)
  );
  NAND _238_ (
    .A(_093_),
    .B(_092_),
    .Y(_000_[10])
  );
  NAND _239_ (
    .A(data_in[11]),
    .B(selector),
    .Y(_094_)
  );
  NAND _240_ (
    .A(lane_0[11]),
    .B(_002_),
    .Y(_095_)
  );
  NAND _241_ (
    .A(_095_),
    .B(_094_),
    .Y(_000_[11])
  );
  NAND _242_ (
    .A(data_in[12]),
    .B(selector),
    .Y(_096_)
  );
  NAND _243_ (
    .A(lane_0[12]),
    .B(_002_),
    .Y(_097_)
  );
  NAND _244_ (
    .A(_097_),
    .B(_096_),
    .Y(_000_[12])
  );
  NAND _245_ (
    .A(data_in[13]),
    .B(selector),
    .Y(_098_)
  );
  NAND _246_ (
    .A(lane_0[13]),
    .B(_002_),
    .Y(_099_)
  );
  NAND _247_ (
    .A(_099_),
    .B(_098_),
    .Y(_000_[13])
  );
  NAND _248_ (
    .A(data_in[14]),
    .B(selector),
    .Y(_100_)
  );
  NAND _249_ (
    .A(lane_0[14]),
    .B(_002_),
    .Y(_101_)
  );
  NAND _250_ (
    .A(_101_),
    .B(_100_),
    .Y(_000_[14])
  );
  NAND _251_ (
    .A(data_in[15]),
    .B(selector),
    .Y(_102_)
  );
  NAND _252_ (
    .A(lane_0[15]),
    .B(_002_),
    .Y(_103_)
  );
  NAND _253_ (
    .A(_103_),
    .B(_102_),
    .Y(_000_[15])
  );
  NAND _254_ (
    .A(data_in[16]),
    .B(selector),
    .Y(_104_)
  );
  NAND _255_ (
    .A(lane_0[16]),
    .B(_002_),
    .Y(_105_)
  );
  NAND _256_ (
    .A(_105_),
    .B(_104_),
    .Y(_000_[16])
  );
  NAND _257_ (
    .A(data_in[17]),
    .B(selector),
    .Y(_106_)
  );
  NAND _258_ (
    .A(lane_0[17]),
    .B(_002_),
    .Y(_107_)
  );
  NAND _259_ (
    .A(_107_),
    .B(_106_),
    .Y(_000_[17])
  );
  NAND _260_ (
    .A(data_in[18]),
    .B(selector),
    .Y(_108_)
  );
  NAND _261_ (
    .A(lane_0[18]),
    .B(_002_),
    .Y(_109_)
  );
  NAND _262_ (
    .A(_109_),
    .B(_108_),
    .Y(_000_[18])
  );
  NAND _263_ (
    .A(data_in[19]),
    .B(selector),
    .Y(_110_)
  );
  NAND _264_ (
    .A(lane_0[19]),
    .B(_002_),
    .Y(_111_)
  );
  NAND _265_ (
    .A(_111_),
    .B(_110_),
    .Y(_000_[19])
  );
  NAND _266_ (
    .A(data_in[20]),
    .B(selector),
    .Y(_112_)
  );
  NAND _267_ (
    .A(lane_0[20]),
    .B(_002_),
    .Y(_113_)
  );
  NAND _268_ (
    .A(_113_),
    .B(_112_),
    .Y(_000_[20])
  );
  NAND _269_ (
    .A(data_in[21]),
    .B(selector),
    .Y(_114_)
  );
  NAND _270_ (
    .A(lane_0[21]),
    .B(_002_),
    .Y(_115_)
  );
  NAND _271_ (
    .A(_115_),
    .B(_114_),
    .Y(_000_[21])
  );
  NAND _272_ (
    .A(data_in[22]),
    .B(selector),
    .Y(_116_)
  );
  NAND _273_ (
    .A(lane_0[22]),
    .B(_002_),
    .Y(_117_)
  );
  NAND _274_ (
    .A(_117_),
    .B(_116_),
    .Y(_000_[22])
  );
  NAND _275_ (
    .A(data_in[23]),
    .B(selector),
    .Y(_118_)
  );
  NAND _276_ (
    .A(lane_0[23]),
    .B(_002_),
    .Y(_119_)
  );
  NAND _277_ (
    .A(_119_),
    .B(_118_),
    .Y(_000_[23])
  );
  NAND _278_ (
    .A(data_in[24]),
    .B(selector),
    .Y(_120_)
  );
  NAND _279_ (
    .A(lane_0[24]),
    .B(_002_),
    .Y(_121_)
  );
  NAND _280_ (
    .A(_121_),
    .B(_120_),
    .Y(_000_[24])
  );
  NAND _281_ (
    .A(data_in[25]),
    .B(selector),
    .Y(_122_)
  );
  NAND _282_ (
    .A(lane_0[25]),
    .B(_002_),
    .Y(_123_)
  );
  NAND _283_ (
    .A(_123_),
    .B(_122_),
    .Y(_000_[25])
  );
  NAND _284_ (
    .A(data_in[26]),
    .B(selector),
    .Y(_124_)
  );
  NAND _285_ (
    .A(lane_0[26]),
    .B(_002_),
    .Y(_125_)
  );
  NAND _286_ (
    .A(_125_),
    .B(_124_),
    .Y(_000_[26])
  );
  NAND _287_ (
    .A(data_in[27]),
    .B(selector),
    .Y(_126_)
  );
  NAND _288_ (
    .A(lane_0[27]),
    .B(_002_),
    .Y(_127_)
  );
  NAND _289_ (
    .A(_127_),
    .B(_126_),
    .Y(_000_[27])
  );
  NAND _290_ (
    .A(data_in[28]),
    .B(selector),
    .Y(_128_)
  );
  NAND _291_ (
    .A(lane_0[28]),
    .B(_002_),
    .Y(_129_)
  );
  NAND _292_ (
    .A(_129_),
    .B(_128_),
    .Y(_000_[28])
  );
  NAND _293_ (
    .A(data_in[29]),
    .B(selector),
    .Y(_130_)
  );
  NAND _294_ (
    .A(lane_0[29]),
    .B(_002_),
    .Y(_131_)
  );
  NAND _295_ (
    .A(_131_),
    .B(_130_),
    .Y(_000_[29])
  );
  NAND _296_ (
    .A(data_in[30]),
    .B(selector),
    .Y(_132_)
  );
  NAND _297_ (
    .A(lane_0[30]),
    .B(_002_),
    .Y(_133_)
  );
  NAND _298_ (
    .A(_133_),
    .B(_132_),
    .Y(_000_[30])
  );
  NAND _299_ (
    .A(data_in[31]),
    .B(selector),
    .Y(_134_)
  );
  NAND _300_ (
    .A(lane_0[31]),
    .B(_002_),
    .Y(_135_)
  );
  NAND _301_ (
    .A(_135_),
    .B(_134_),
    .Y(_000_[31])
  );
  NAND _302_ (
    .A(valid1),
    .B(selector),
    .Y(_136_)
  );
  NAND _303_ (
    .A(valid),
    .B(_002_),
    .Y(_137_)
  );
  NAND _304_ (
    .A(_137_),
    .B(_136_),
    .Y(_004_)
  );
  NAND _305_ (
    .A(valid),
    .B(selector),
    .Y(_138_)
  );
  NAND _306_ (
    .A(valid0),
    .B(_002_),
    .Y(_139_)
  );
  NAND _307_ (
    .A(_139_),
    .B(_138_),
    .Y(_003_)
  );
  NAND _308_ (
    .A(lane_1[0]),
    .B(selector),
    .Y(_140_)
  );
  NAND _309_ (
    .A(_002_),
    .B(data_in[0]),
    .Y(_141_)
  );
  NAND _310_ (
    .A(_141_),
    .B(_140_),
    .Y(_001_[0])
  );
  NAND _311_ (
    .A(lane_1[1]),
    .B(selector),
    .Y(_142_)
  );
  NAND _312_ (
    .A(data_in[1]),
    .B(_002_),
    .Y(_143_)
  );
  NAND _313_ (
    .A(_143_),
    .B(_142_),
    .Y(_001_[1])
  );
  NAND _314_ (
    .A(lane_1[2]),
    .B(selector),
    .Y(_144_)
  );
  NAND _315_ (
    .A(data_in[2]),
    .B(_002_),
    .Y(_145_)
  );
  NAND _316_ (
    .A(_145_),
    .B(_144_),
    .Y(_001_[2])
  );
  NAND _317_ (
    .A(lane_1[3]),
    .B(selector),
    .Y(_146_)
  );
  NAND _318_ (
    .A(data_in[3]),
    .B(_002_),
    .Y(_147_)
  );
  NAND _319_ (
    .A(_147_),
    .B(_146_),
    .Y(_001_[3])
  );
  NAND _320_ (
    .A(lane_1[4]),
    .B(selector),
    .Y(_148_)
  );
  NAND _321_ (
    .A(data_in[4]),
    .B(_002_),
    .Y(_149_)
  );
  NAND _322_ (
    .A(_149_),
    .B(_148_),
    .Y(_001_[4])
  );
  NAND _323_ (
    .A(lane_1[5]),
    .B(selector),
    .Y(_150_)
  );
  NAND _324_ (
    .A(data_in[5]),
    .B(_002_),
    .Y(_151_)
  );
  NAND _325_ (
    .A(_151_),
    .B(_150_),
    .Y(_001_[5])
  );
  NAND _326_ (
    .A(lane_1[6]),
    .B(selector),
    .Y(_152_)
  );
  NAND _327_ (
    .A(data_in[6]),
    .B(_002_),
    .Y(_153_)
  );
  NAND _328_ (
    .A(_153_),
    .B(_152_),
    .Y(_001_[6])
  );
  NAND _329_ (
    .A(lane_1[7]),
    .B(selector),
    .Y(_154_)
  );
  NAND _330_ (
    .A(data_in[7]),
    .B(_002_),
    .Y(_155_)
  );
  NAND _331_ (
    .A(_155_),
    .B(_154_),
    .Y(_001_[7])
  );
  NAND _332_ (
    .A(lane_1[8]),
    .B(selector),
    .Y(_156_)
  );
  NAND _333_ (
    .A(data_in[8]),
    .B(_002_),
    .Y(_157_)
  );
  NAND _334_ (
    .A(_157_),
    .B(_156_),
    .Y(_001_[8])
  );
  NAND _335_ (
    .A(lane_1[9]),
    .B(selector),
    .Y(_158_)
  );
  NAND _336_ (
    .A(data_in[9]),
    .B(_002_),
    .Y(_159_)
  );
  NAND _337_ (
    .A(_159_),
    .B(_158_),
    .Y(_001_[9])
  );
  NAND _338_ (
    .A(lane_1[10]),
    .B(selector),
    .Y(_160_)
  );
  NAND _339_ (
    .A(data_in[10]),
    .B(_002_),
    .Y(_161_)
  );
  NAND _340_ (
    .A(_161_),
    .B(_160_),
    .Y(_001_[10])
  );
  NAND _341_ (
    .A(lane_1[11]),
    .B(selector),
    .Y(_162_)
  );
  NAND _342_ (
    .A(data_in[11]),
    .B(_002_),
    .Y(_163_)
  );
  NAND _343_ (
    .A(_163_),
    .B(_162_),
    .Y(_001_[11])
  );
  NAND _344_ (
    .A(lane_1[12]),
    .B(selector),
    .Y(_164_)
  );
  NAND _345_ (
    .A(data_in[12]),
    .B(_002_),
    .Y(_165_)
  );
  NAND _346_ (
    .A(_165_),
    .B(_164_),
    .Y(_001_[12])
  );
  NAND _347_ (
    .A(lane_1[13]),
    .B(selector),
    .Y(_166_)
  );
  NAND _348_ (
    .A(data_in[13]),
    .B(_002_),
    .Y(_167_)
  );
  NAND _349_ (
    .A(_167_),
    .B(_166_),
    .Y(_001_[13])
  );
  NAND _350_ (
    .A(lane_1[14]),
    .B(selector),
    .Y(_168_)
  );
  NAND _351_ (
    .A(data_in[14]),
    .B(_002_),
    .Y(_169_)
  );
  NAND _352_ (
    .A(_169_),
    .B(_168_),
    .Y(_001_[14])
  );
  NAND _353_ (
    .A(lane_1[15]),
    .B(selector),
    .Y(_170_)
  );
  NAND _354_ (
    .A(data_in[15]),
    .B(_002_),
    .Y(_171_)
  );
  NAND _355_ (
    .A(_171_),
    .B(_170_),
    .Y(_001_[15])
  );
  NAND _356_ (
    .A(lane_1[16]),
    .B(selector),
    .Y(_172_)
  );
  NAND _357_ (
    .A(data_in[16]),
    .B(_002_),
    .Y(_173_)
  );
  NAND _358_ (
    .A(_173_),
    .B(_172_),
    .Y(_001_[16])
  );
  NAND _359_ (
    .A(lane_1[17]),
    .B(selector),
    .Y(_174_)
  );
  NAND _360_ (
    .A(data_in[17]),
    .B(_002_),
    .Y(_175_)
  );
  NAND _361_ (
    .A(_175_),
    .B(_174_),
    .Y(_001_[17])
  );
  NAND _362_ (
    .A(lane_1[18]),
    .B(selector),
    .Y(_176_)
  );
  NAND _363_ (
    .A(data_in[18]),
    .B(_002_),
    .Y(_177_)
  );
  NAND _364_ (
    .A(_177_),
    .B(_176_),
    .Y(_001_[18])
  );
  NAND _365_ (
    .A(lane_1[19]),
    .B(selector),
    .Y(_178_)
  );
  NAND _366_ (
    .A(data_in[19]),
    .B(_002_),
    .Y(_179_)
  );
  NAND _367_ (
    .A(_179_),
    .B(_178_),
    .Y(_001_[19])
  );
  NAND _368_ (
    .A(lane_1[20]),
    .B(selector),
    .Y(_180_)
  );
  NAND _369_ (
    .A(data_in[20]),
    .B(_002_),
    .Y(_181_)
  );
  NAND _370_ (
    .A(_181_),
    .B(_180_),
    .Y(_001_[20])
  );
  NAND _371_ (
    .A(lane_1[21]),
    .B(selector),
    .Y(_182_)
  );
  NAND _372_ (
    .A(data_in[21]),
    .B(_002_),
    .Y(_183_)
  );
  NAND _373_ (
    .A(_183_),
    .B(_182_),
    .Y(_001_[21])
  );
  NAND _374_ (
    .A(lane_1[22]),
    .B(selector),
    .Y(_184_)
  );
  NAND _375_ (
    .A(data_in[22]),
    .B(_002_),
    .Y(_185_)
  );
  NAND _376_ (
    .A(_185_),
    .B(_184_),
    .Y(_001_[22])
  );
  NAND _377_ (
    .A(lane_1[23]),
    .B(selector),
    .Y(_186_)
  );
  NAND _378_ (
    .A(data_in[23]),
    .B(_002_),
    .Y(_187_)
  );
  NAND _379_ (
    .A(_187_),
    .B(_186_),
    .Y(_001_[23])
  );
  NAND _380_ (
    .A(lane_1[24]),
    .B(selector),
    .Y(_188_)
  );
  NAND _381_ (
    .A(data_in[24]),
    .B(_002_),
    .Y(_189_)
  );
  NAND _382_ (
    .A(_189_),
    .B(_188_),
    .Y(_001_[24])
  );
  NAND _383_ (
    .A(lane_1[25]),
    .B(selector),
    .Y(_190_)
  );
  NAND _384_ (
    .A(data_in[25]),
    .B(_002_),
    .Y(_191_)
  );
  NAND _385_ (
    .A(_191_),
    .B(_190_),
    .Y(_001_[25])
  );
  NAND _386_ (
    .A(lane_1[26]),
    .B(selector),
    .Y(_192_)
  );
  NAND _387_ (
    .A(data_in[26]),
    .B(_002_),
    .Y(_193_)
  );
  NAND _388_ (
    .A(_193_),
    .B(_192_),
    .Y(_001_[26])
  );
  NAND _389_ (
    .A(lane_1[27]),
    .B(selector),
    .Y(_194_)
  );
  NAND _390_ (
    .A(data_in[27]),
    .B(_002_),
    .Y(_195_)
  );
  NAND _391_ (
    .A(_195_),
    .B(_194_),
    .Y(_001_[27])
  );
  NAND _392_ (
    .A(lane_1[28]),
    .B(selector),
    .Y(_196_)
  );
  NAND _393_ (
    .A(data_in[28]),
    .B(_002_),
    .Y(_197_)
  );
  NAND _394_ (
    .A(_197_),
    .B(_196_),
    .Y(_001_[28])
  );
  NAND _395_ (
    .A(lane_1[29]),
    .B(selector),
    .Y(_198_)
  );
  NAND _396_ (
    .A(data_in[29]),
    .B(_002_),
    .Y(_199_)
  );
  NAND _397_ (
    .A(_199_),
    .B(_198_),
    .Y(_001_[29])
  );
  NAND _398_ (
    .A(lane_1[30]),
    .B(selector),
    .Y(_200_)
  );
  NAND _399_ (
    .A(data_in[30]),
    .B(_002_),
    .Y(_201_)
  );
  NAND _400_ (
    .A(_201_),
    .B(_200_),
    .Y(_001_[30])
  );
  NAND _401_ (
    .A(lane_1[31]),
    .B(selector),
    .Y(_202_)
  );
  NAND _402_ (
    .A(data_in[31]),
    .B(_002_),
    .Y(_203_)
  );
  NAND _403_ (
    .A(_203_),
    .B(_202_),
    .Y(_001_[31])
  );
  NOT _404_ (
    .A(reset_L),
    .Y(_006_)
  );
  NOT _405_ (
    .A(reset_L),
    .Y(_007_)
  );
  NOT _406_ (
    .A(reset_L),
    .Y(_008_)
  );
  NOT _407_ (
    .A(reset_L),
    .Y(_009_)
  );
  NOT _408_ (
    .A(reset_L),
    .Y(_010_)
  );
  NOT _409_ (
    .A(reset_L),
    .Y(_011_)
  );
  NOT _410_ (
    .A(reset_L),
    .Y(_012_)
  );
  NOT _411_ (
    .A(reset_L),
    .Y(_013_)
  );
  NOT _412_ (
    .A(reset_L),
    .Y(_014_)
  );
  NOT _413_ (
    .A(reset_L),
    .Y(_015_)
  );
  NOT _414_ (
    .A(reset_L),
    .Y(_016_)
  );
  NOT _415_ (
    .A(reset_L),
    .Y(_017_)
  );
  NOT _416_ (
    .A(reset_L),
    .Y(_018_)
  );
  NOT _417_ (
    .A(reset_L),
    .Y(_019_)
  );
  NOT _418_ (
    .A(reset_L),
    .Y(_020_)
  );
  NOT _419_ (
    .A(reset_L),
    .Y(_021_)
  );
  NOT _420_ (
    .A(reset_L),
    .Y(_022_)
  );
  NOT _421_ (
    .A(reset_L),
    .Y(_023_)
  );
  NOT _422_ (
    .A(reset_L),
    .Y(_024_)
  );
  NOT _423_ (
    .A(reset_L),
    .Y(_025_)
  );
  NOT _424_ (
    .A(reset_L),
    .Y(_026_)
  );
  NOT _425_ (
    .A(reset_L),
    .Y(_027_)
  );
  NOT _426_ (
    .A(reset_L),
    .Y(_028_)
  );
  NOT _427_ (
    .A(reset_L),
    .Y(_029_)
  );
  NOT _428_ (
    .A(reset_L),
    .Y(_030_)
  );
  NOT _429_ (
    .A(reset_L),
    .Y(_031_)
  );
  NOT _430_ (
    .A(reset_L),
    .Y(_032_)
  );
  NOT _431_ (
    .A(reset_L),
    .Y(_033_)
  );
  NOT _432_ (
    .A(reset_L),
    .Y(_034_)
  );
  NOT _433_ (
    .A(reset_L),
    .Y(_035_)
  );
  NOT _434_ (
    .A(reset_L),
    .Y(_036_)
  );
  NOT _435_ (
    .A(reset_L),
    .Y(_037_)
  );
  NOT _436_ (
    .A(reset_L),
    .Y(_038_)
  );
  NOT _437_ (
    .A(reset_L),
    .Y(_039_)
  );
  NOT _438_ (
    .A(reset_L),
    .Y(_040_)
  );
  NOT _439_ (
    .A(reset_L),
    .Y(_041_)
  );
  NOT _440_ (
    .A(reset_L),
    .Y(_042_)
  );
  NOT _441_ (
    .A(reset_L),
    .Y(_043_)
  );
  NOT _442_ (
    .A(reset_L),
    .Y(_044_)
  );
  NOT _443_ (
    .A(reset_L),
    .Y(_045_)
  );
  NOT _444_ (
    .A(reset_L),
    .Y(_046_)
  );
  NOT _445_ (
    .A(reset_L),
    .Y(_047_)
  );
  NOT _446_ (
    .A(reset_L),
    .Y(_048_)
  );
  NOT _447_ (
    .A(reset_L),
    .Y(_049_)
  );
  NOT _448_ (
    .A(reset_L),
    .Y(_050_)
  );
  NOT _449_ (
    .A(reset_L),
    .Y(_051_)
  );
  NOT _450_ (
    .A(reset_L),
    .Y(_052_)
  );
  NOT _451_ (
    .A(reset_L),
    .Y(_053_)
  );
  NOT _452_ (
    .A(reset_L),
    .Y(_054_)
  );
  NOT _453_ (
    .A(reset_L),
    .Y(_055_)
  );
  NOT _454_ (
    .A(reset_L),
    .Y(_056_)
  );
  NOT _455_ (
    .A(reset_L),
    .Y(_057_)
  );
  NOT _456_ (
    .A(reset_L),
    .Y(_058_)
  );
  NOT _457_ (
    .A(reset_L),
    .Y(_059_)
  );
  NOT _458_ (
    .A(reset_L),
    .Y(_060_)
  );
  NOT _459_ (
    .A(reset_L),
    .Y(_061_)
  );
  NOT _460_ (
    .A(reset_L),
    .Y(_062_)
  );
  NOT _461_ (
    .A(reset_L),
    .Y(_063_)
  );
  NOT _462_ (
    .A(reset_L),
    .Y(_064_)
  );
  NOT _463_ (
    .A(reset_L),
    .Y(_065_)
  );
  NOT _464_ (
    .A(reset_L),
    .Y(_066_)
  );
  NOT _465_ (
    .A(reset_L),
    .Y(_067_)
  );
  NOT _466_ (
    .A(reset_L),
    .Y(_068_)
  );
  NOT _467_ (
    .A(reset_L),
    .Y(_069_)
  );
  NOT _468_ (
    .A(reset_L),
    .Y(_070_)
  );
  NOT _469_ (
    .A(reset_L),
    .Y(_071_)
  );
  DFFSR _470_ (
    .C(clock2),
    .D(_000_[0]),
    .Q(lane_0[0]),
    .R(_006_),
    .S(1'b0)
  );
  DFFSR _471_ (
    .C(clock2),
    .D(_000_[1]),
    .Q(lane_0[1]),
    .R(_007_),
    .S(1'b0)
  );
  DFFSR _472_ (
    .C(clock2),
    .D(_000_[2]),
    .Q(lane_0[2]),
    .R(_008_),
    .S(1'b0)
  );
  DFFSR _473_ (
    .C(clock2),
    .D(_000_[3]),
    .Q(lane_0[3]),
    .R(_009_),
    .S(1'b0)
  );
  DFFSR _474_ (
    .C(clock2),
    .D(_000_[4]),
    .Q(lane_0[4]),
    .R(_010_),
    .S(1'b0)
  );
  DFFSR _475_ (
    .C(clock2),
    .D(_000_[5]),
    .Q(lane_0[5]),
    .R(_011_),
    .S(1'b0)
  );
  DFFSR _476_ (
    .C(clock2),
    .D(_000_[6]),
    .Q(lane_0[6]),
    .R(_012_),
    .S(1'b0)
  );
  DFFSR _477_ (
    .C(clock2),
    .D(_000_[7]),
    .Q(lane_0[7]),
    .R(_013_),
    .S(1'b0)
  );
  DFFSR _478_ (
    .C(clock2),
    .D(_000_[8]),
    .Q(lane_0[8]),
    .R(_014_),
    .S(1'b0)
  );
  DFFSR _479_ (
    .C(clock2),
    .D(_000_[9]),
    .Q(lane_0[9]),
    .R(_015_),
    .S(1'b0)
  );
  DFFSR _480_ (
    .C(clock2),
    .D(_000_[10]),
    .Q(lane_0[10]),
    .R(_016_),
    .S(1'b0)
  );
  DFFSR _481_ (
    .C(clock2),
    .D(_000_[11]),
    .Q(lane_0[11]),
    .R(_017_),
    .S(1'b0)
  );
  DFFSR _482_ (
    .C(clock2),
    .D(_000_[12]),
    .Q(lane_0[12]),
    .R(_018_),
    .S(1'b0)
  );
  DFFSR _483_ (
    .C(clock2),
    .D(_000_[13]),
    .Q(lane_0[13]),
    .R(_019_),
    .S(1'b0)
  );
  DFFSR _484_ (
    .C(clock2),
    .D(_000_[14]),
    .Q(lane_0[14]),
    .R(_020_),
    .S(1'b0)
  );
  DFFSR _485_ (
    .C(clock2),
    .D(_000_[15]),
    .Q(lane_0[15]),
    .R(_021_),
    .S(1'b0)
  );
  DFFSR _486_ (
    .C(clock2),
    .D(_000_[16]),
    .Q(lane_0[16]),
    .R(_022_),
    .S(1'b0)
  );
  DFFSR _487_ (
    .C(clock2),
    .D(_000_[17]),
    .Q(lane_0[17]),
    .R(_023_),
    .S(1'b0)
  );
  DFFSR _488_ (
    .C(clock2),
    .D(_000_[18]),
    .Q(lane_0[18]),
    .R(_024_),
    .S(1'b0)
  );
  DFFSR _489_ (
    .C(clock2),
    .D(_000_[19]),
    .Q(lane_0[19]),
    .R(_025_),
    .S(1'b0)
  );
  DFFSR _490_ (
    .C(clock2),
    .D(_000_[20]),
    .Q(lane_0[20]),
    .R(_026_),
    .S(1'b0)
  );
  DFFSR _491_ (
    .C(clock2),
    .D(_000_[21]),
    .Q(lane_0[21]),
    .R(_027_),
    .S(1'b0)
  );
  DFFSR _492_ (
    .C(clock2),
    .D(_000_[22]),
    .Q(lane_0[22]),
    .R(_028_),
    .S(1'b0)
  );
  DFFSR _493_ (
    .C(clock2),
    .D(_000_[23]),
    .Q(lane_0[23]),
    .R(_029_),
    .S(1'b0)
  );
  DFFSR _494_ (
    .C(clock2),
    .D(_000_[24]),
    .Q(lane_0[24]),
    .R(_030_),
    .S(1'b0)
  );
  DFFSR _495_ (
    .C(clock2),
    .D(_000_[25]),
    .Q(lane_0[25]),
    .R(_031_),
    .S(1'b0)
  );
  DFFSR _496_ (
    .C(clock2),
    .D(_000_[26]),
    .Q(lane_0[26]),
    .R(_032_),
    .S(1'b0)
  );
  DFFSR _497_ (
    .C(clock2),
    .D(_000_[27]),
    .Q(lane_0[27]),
    .R(_033_),
    .S(1'b0)
  );
  DFFSR _498_ (
    .C(clock2),
    .D(_000_[28]),
    .Q(lane_0[28]),
    .R(_034_),
    .S(1'b0)
  );
  DFFSR _499_ (
    .C(clock2),
    .D(_000_[29]),
    .Q(lane_0[29]),
    .R(_035_),
    .S(1'b0)
  );
  DFFSR _500_ (
    .C(clock2),
    .D(_000_[30]),
    .Q(lane_0[30]),
    .R(_036_),
    .S(1'b0)
  );
  DFFSR _501_ (
    .C(clock2),
    .D(_000_[31]),
    .Q(lane_0[31]),
    .R(_037_),
    .S(1'b0)
  );
  DFFSR _502_ (
    .C(clock2),
    .D(_001_[0]),
    .Q(lane_1[0]),
    .R(_038_),
    .S(1'b0)
  );
  DFFSR _503_ (
    .C(clock2),
    .D(_001_[1]),
    .Q(lane_1[1]),
    .R(_039_),
    .S(1'b0)
  );
  DFFSR _504_ (
    .C(clock2),
    .D(_001_[2]),
    .Q(lane_1[2]),
    .R(_040_),
    .S(1'b0)
  );
  DFFSR _505_ (
    .C(clock2),
    .D(_001_[3]),
    .Q(lane_1[3]),
    .R(_041_),
    .S(1'b0)
  );
  DFFSR _506_ (
    .C(clock2),
    .D(_001_[4]),
    .Q(lane_1[4]),
    .R(_042_),
    .S(1'b0)
  );
  DFFSR _507_ (
    .C(clock2),
    .D(_001_[5]),
    .Q(lane_1[5]),
    .R(_043_),
    .S(1'b0)
  );
  DFFSR _508_ (
    .C(clock2),
    .D(_001_[6]),
    .Q(lane_1[6]),
    .R(_044_),
    .S(1'b0)
  );
  DFFSR _509_ (
    .C(clock2),
    .D(_001_[7]),
    .Q(lane_1[7]),
    .R(_045_),
    .S(1'b0)
  );
  DFFSR _510_ (
    .C(clock2),
    .D(_001_[8]),
    .Q(lane_1[8]),
    .R(_046_),
    .S(1'b0)
  );
  DFFSR _511_ (
    .C(clock2),
    .D(_001_[9]),
    .Q(lane_1[9]),
    .R(_047_),
    .S(1'b0)
  );
  DFFSR _512_ (
    .C(clock2),
    .D(_001_[10]),
    .Q(lane_1[10]),
    .R(_048_),
    .S(1'b0)
  );
  DFFSR _513_ (
    .C(clock2),
    .D(_001_[11]),
    .Q(lane_1[11]),
    .R(_049_),
    .S(1'b0)
  );
  DFFSR _514_ (
    .C(clock2),
    .D(_001_[12]),
    .Q(lane_1[12]),
    .R(_050_),
    .S(1'b0)
  );
  DFFSR _515_ (
    .C(clock2),
    .D(_001_[13]),
    .Q(lane_1[13]),
    .R(_051_),
    .S(1'b0)
  );
  DFFSR _516_ (
    .C(clock2),
    .D(_001_[14]),
    .Q(lane_1[14]),
    .R(_052_),
    .S(1'b0)
  );
  DFFSR _517_ (
    .C(clock2),
    .D(_001_[15]),
    .Q(lane_1[15]),
    .R(_053_),
    .S(1'b0)
  );
  DFFSR _518_ (
    .C(clock2),
    .D(_001_[16]),
    .Q(lane_1[16]),
    .R(_054_),
    .S(1'b0)
  );
  DFFSR _519_ (
    .C(clock2),
    .D(_001_[17]),
    .Q(lane_1[17]),
    .R(_055_),
    .S(1'b0)
  );
  DFFSR _520_ (
    .C(clock2),
    .D(_001_[18]),
    .Q(lane_1[18]),
    .R(_056_),
    .S(1'b0)
  );
  DFFSR _521_ (
    .C(clock2),
    .D(_001_[19]),
    .Q(lane_1[19]),
    .R(_057_),
    .S(1'b0)
  );
  DFFSR _522_ (
    .C(clock2),
    .D(_001_[20]),
    .Q(lane_1[20]),
    .R(_058_),
    .S(1'b0)
  );
  DFFSR _523_ (
    .C(clock2),
    .D(_001_[21]),
    .Q(lane_1[21]),
    .R(_059_),
    .S(1'b0)
  );
  DFFSR _524_ (
    .C(clock2),
    .D(_001_[22]),
    .Q(lane_1[22]),
    .R(_060_),
    .S(1'b0)
  );
  DFFSR _525_ (
    .C(clock2),
    .D(_001_[23]),
    .Q(lane_1[23]),
    .R(_061_),
    .S(1'b0)
  );
  DFFSR _526_ (
    .C(clock2),
    .D(_001_[24]),
    .Q(lane_1[24]),
    .R(_062_),
    .S(1'b0)
  );
  DFFSR _527_ (
    .C(clock2),
    .D(_001_[25]),
    .Q(lane_1[25]),
    .R(_063_),
    .S(1'b0)
  );
  DFFSR _528_ (
    .C(clock2),
    .D(_001_[26]),
    .Q(lane_1[26]),
    .R(_064_),
    .S(1'b0)
  );
  DFFSR _529_ (
    .C(clock2),
    .D(_001_[27]),
    .Q(lane_1[27]),
    .R(_065_),
    .S(1'b0)
  );
  DFFSR _530_ (
    .C(clock2),
    .D(_001_[28]),
    .Q(lane_1[28]),
    .R(_066_),
    .S(1'b0)
  );
  DFFSR _531_ (
    .C(clock2),
    .D(_001_[29]),
    .Q(lane_1[29]),
    .R(_067_),
    .S(1'b0)
  );
  DFFSR _532_ (
    .C(clock2),
    .D(_001_[30]),
    .Q(lane_1[30]),
    .R(_068_),
    .S(1'b0)
  );
  DFFSR _533_ (
    .C(clock2),
    .D(_001_[31]),
    .Q(lane_1[31]),
    .R(_069_),
    .S(1'b0)
  );
  DFFSR _534_ (
    .C(clock2),
    .D(_003_),
    .Q(valid0),
    .R(_070_),
    .S(1'b0)
  );
  DFFSR _535_ (
    .C(clock2),
    .D(_004_),
    .Q(valid1),
    .R(_071_),
    .S(1'b0)
  );
  DFFSR _536_ (
    .C(clock2),
    .D(_002_),
    .Q(selector),
    .R(_005_),
    .S(1'b0)
  );
endmodule
