/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 4.8.4-2ubuntu1~14.04.3 -O2 -fstack-protector -fPIC -Os) */

(* top =  1  *)
(* src = "paralelo_serieS.v:1" *)
module paralelo_serieS(data_in, data2sent, data_out, counterBC, valid, clock32, clock4, reset_L);
  (* src = "paralelo_serieS.v:9" *)
  wire [15:0] _000_;
  (* src = "paralelo_serieS.v:9" *)
  wire [7:0] _001_;
  (* src = "paralelo_serieS.v:9" *)
  wire _002_;
  (* src = "paralelo_serieS.v:9" *)
  wire [2:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  (* src = "paralelo_serieS.v:6" *)
  input clock32;
  (* src = "paralelo_serieS.v:6" *)
  input clock4;
  (* src = "paralelo_serieS.v:5" *)
  output [15:0] counterBC;
  (* src = "paralelo_serieS.v:3" *)
  output [7:0] data2sent;
  (* src = "paralelo_serieS.v:2" *)
  input [7:0] data_in;
  (* src = "paralelo_serieS.v:4" *)
  output data_out;
  (* src = "paralelo_serieS.v:6" *)
  input reset_L;
  (* src = "paralelo_serieS.v:8" *)
  wire [2:0] select;
  (* src = "paralelo_serieS.v:6" *)
  input valid;
  NOR _166_ (
    .A(_014_),
    .B(_160_),
    .Y(_015_)
  );
  NOR _167_ (
    .A(_010_),
    .B(counterBC[3]),
    .Y(_016_)
  );
  NOR _168_ (
    .A(_016_),
    .B(_015_),
    .Y(_000_[3])
  );
  NOR _169_ (
    .A(_015_),
    .B(counterBC[4]),
    .Y(_017_)
  );
  NAND _170_ (
    .A(_015_),
    .B(counterBC[4]),
    .Y(_018_)
  );
  NOT _171_ (
    .A(_018_),
    .Y(_019_)
  );
  NOR _172_ (
    .A(_019_),
    .B(_017_),
    .Y(_000_[4])
  );
  NOR _173_ (
    .A(_019_),
    .B(counterBC[5]),
    .Y(_020_)
  );
  NOT _174_ (
    .A(counterBC[5]),
    .Y(_021_)
  );
  NOR _175_ (
    .A(_018_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _176_ (
    .A(_022_),
    .B(_020_),
    .Y(_000_[5])
  );
  NOR _177_ (
    .A(_022_),
    .B(counterBC[6]),
    .Y(_023_)
  );
  NOT _178_ (
    .A(counterBC[6]),
    .Y(_024_)
  );
  NAND _179_ (
    .A(counterBC[5]),
    .B(counterBC[4]),
    .Y(_025_)
  );
  NOT _180_ (
    .A(_025_),
    .Y(_026_)
  );
  NAND _181_ (
    .A(_026_),
    .B(_015_),
    .Y(_027_)
  );
  NOR _182_ (
    .A(_027_),
    .B(_024_),
    .Y(_028_)
  );
  NOR _183_ (
    .A(_028_),
    .B(_023_),
    .Y(_000_[6])
  );
  NOR _184_ (
    .A(_028_),
    .B(counterBC[7]),
    .Y(_029_)
  );
  NAND _185_ (
    .A(_028_),
    .B(counterBC[7]),
    .Y(_030_)
  );
  NOT _186_ (
    .A(_030_),
    .Y(_031_)
  );
  NOR _187_ (
    .A(_031_),
    .B(_029_),
    .Y(_000_[7])
  );
  NOR _188_ (
    .A(_031_),
    .B(counterBC[8]),
    .Y(_032_)
  );
  NOT _189_ (
    .A(counterBC[8]),
    .Y(_033_)
  );
  NOR _190_ (
    .A(_030_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _191_ (
    .A(_034_),
    .B(_032_),
    .Y(_000_[8])
  );
  NOR _192_ (
    .A(_034_),
    .B(counterBC[9]),
    .Y(_035_)
  );
  NOT _193_ (
    .A(counterBC[9]),
    .Y(_036_)
  );
  NOT _194_ (
    .A(_034_),
    .Y(_037_)
  );
  NOR _195_ (
    .A(_037_),
    .B(_036_),
    .Y(_038_)
  );
  NOR _196_ (
    .A(_038_),
    .B(_035_),
    .Y(_000_[9])
  );
  NOT _197_ (
    .A(counterBC[7]),
    .Y(_039_)
  );
  NOR _198_ (
    .A(_039_),
    .B(_024_),
    .Y(_041_)
  );
  NOR _199_ (
    .A(_036_),
    .B(_033_),
    .Y(_043_)
  );
  NAND _200_ (
    .A(_043_),
    .B(_041_),
    .Y(_045_)
  );
  NOR _201_ (
    .A(_045_),
    .B(_025_),
    .Y(_047_)
  );
  NAND _202_ (
    .A(_047_),
    .B(_015_),
    .Y(_049_)
  );
  NOT _203_ (
    .A(_049_),
    .Y(_051_)
  );
  NOR _204_ (
    .A(_051_),
    .B(counterBC[10]),
    .Y(_053_)
  );
  NOT _205_ (
    .A(counterBC[10]),
    .Y(_055_)
  );
  NOR _206_ (
    .A(_049_),
    .B(_055_),
    .Y(_057_)
  );
  NOR _207_ (
    .A(_057_),
    .B(_053_),
    .Y(_000_[10])
  );
  NOR _208_ (
    .A(_057_),
    .B(counterBC[11]),
    .Y(_060_)
  );
  NAND _209_ (
    .A(_057_),
    .B(counterBC[11]),
    .Y(_062_)
  );
  NOT _210_ (
    .A(_062_),
    .Y(_064_)
  );
  NOR _211_ (
    .A(_064_),
    .B(_060_),
    .Y(_000_[11])
  );
  NOR _212_ (
    .A(_064_),
    .B(counterBC[12]),
    .Y(_067_)
  );
  NOT _213_ (
    .A(counterBC[12]),
    .Y(_069_)
  );
  NOR _214_ (
    .A(_062_),
    .B(_069_),
    .Y(_071_)
  );
  NOR _215_ (
    .A(_071_),
    .B(_067_),
    .Y(_000_[12])
  );
  NOR _216_ (
    .A(_071_),
    .B(counterBC[13]),
    .Y(_074_)
  );
  NOT _217_ (
    .A(counterBC[13]),
    .Y(_076_)
  );
  NOT _218_ (
    .A(counterBC[11]),
    .Y(_078_)
  );
  NOR _219_ (
    .A(_078_),
    .B(_055_),
    .Y(_080_)
  );
  NAND _220_ (
    .A(counterBC[4]),
    .B(counterBC[3]),
    .Y(_082_)
  );
  NOR _221_ (
    .A(_082_),
    .B(_021_),
    .Y(_084_)
  );
  NOT _222_ (
    .A(_084_),
    .Y(_086_)
  );
  NAND _223_ (
    .A(counterBC[7]),
    .B(counterBC[6]),
    .Y(_088_)
  );
  NOR _224_ (
    .A(_088_),
    .B(_165_),
    .Y(_090_)
  );
  NAND _225_ (
    .A(counterBC[2]),
    .B(counterBC[0]),
    .Y(_091_)
  );
  NOR _226_ (
    .A(_091_),
    .B(_036_),
    .Y(_092_)
  );
  NAND _227_ (
    .A(_092_),
    .B(_090_),
    .Y(_093_)
  );
  NOR _228_ (
    .A(_093_),
    .B(_086_),
    .Y(_094_)
  );
  NOR _229_ (
    .A(_160_),
    .B(_033_),
    .Y(_095_)
  );
  NAND _230_ (
    .A(_095_),
    .B(_094_),
    .Y(_096_)
  );
  NOR _231_ (
    .A(_096_),
    .B(_069_),
    .Y(_097_)
  );
  NAND _232_ (
    .A(_097_),
    .B(_080_),
    .Y(_098_)
  );
  NOR _233_ (
    .A(_098_),
    .B(_076_),
    .Y(_099_)
  );
  NOR _234_ (
    .A(_099_),
    .B(_074_),
    .Y(_000_[13])
  );
  NOR _235_ (
    .A(_099_),
    .B(counterBC[14]),
    .Y(_100_)
  );
  NOT _236_ (
    .A(counterBC[14]),
    .Y(_101_)
  );
  NAND _237_ (
    .A(_041_),
    .B(counterBC[8]),
    .Y(_102_)
  );
  NAND _238_ (
    .A(_005_),
    .B(counterBC[2]),
    .Y(_103_)
  );
  NOR _239_ (
    .A(_103_),
    .B(_102_),
    .Y(_104_)
  );
  NAND _240_ (
    .A(_084_),
    .B(counterBC[9]),
    .Y(_105_)
  );
  NOR _241_ (
    .A(_105_),
    .B(_160_),
    .Y(_106_)
  );
  NAND _242_ (
    .A(_106_),
    .B(_104_),
    .Y(_107_)
  );
  NOR _243_ (
    .A(_107_),
    .B(_055_),
    .Y(_108_)
  );
  NAND _244_ (
    .A(_108_),
    .B(counterBC[11]),
    .Y(_109_)
  );
  NOR _245_ (
    .A(_109_),
    .B(_069_),
    .Y(_110_)
  );
  NAND _246_ (
    .A(_110_),
    .B(counterBC[13]),
    .Y(_111_)
  );
  NOR _247_ (
    .A(_111_),
    .B(_101_),
    .Y(_112_)
  );
  NOR _248_ (
    .A(_112_),
    .B(_100_),
    .Y(_000_[14])
  );
  NAND _249_ (
    .A(_099_),
    .B(counterBC[14]),
    .Y(_113_)
  );
  NAND _250_ (
    .A(_113_),
    .B(counterBC[15]),
    .Y(_114_)
  );
  NOT _251_ (
    .A(counterBC[15]),
    .Y(_115_)
  );
  NAND _252_ (
    .A(_112_),
    .B(_115_),
    .Y(_116_)
  );
  NAND _253_ (
    .A(_116_),
    .B(_114_),
    .Y(_000_[15])
  );
  NOT _254_ (
    .A(data_in[6]),
    .Y(_117_)
  );
  NOR _255_ (
    .A(select[1]),
    .B(_003_[0]),
    .Y(_118_)
  );
  NOT _256_ (
    .A(_118_),
    .Y(_119_)
  );
  NOR _257_ (
    .A(_119_),
    .B(_117_),
    .Y(_120_)
  );
  NOR _258_ (
    .A(_120_),
    .B(select[2]),
    .Y(_121_)
  );
  NOT _259_ (
    .A(data_in[4]),
    .Y(_122_)
  );
  NOT _260_ (
    .A(select[1]),
    .Y(_123_)
  );
  NOR _261_ (
    .A(_123_),
    .B(_003_[0]),
    .Y(_124_)
  );
  NOT _262_ (
    .A(_124_),
    .Y(_125_)
  );
  NOR _263_ (
    .A(_125_),
    .B(_122_),
    .Y(_126_)
  );
  NOR _264_ (
    .A(select[1]),
    .B(select[0]),
    .Y(_127_)
  );
  NAND _265_ (
    .A(_127_),
    .B(data_in[7]),
    .Y(_128_)
  );
  NOR _266_ (
    .A(_123_),
    .B(select[0]),
    .Y(_129_)
  );
  NAND _267_ (
    .A(_129_),
    .B(data_in[5]),
    .Y(_130_)
  );
  NAND _268_ (
    .A(_130_),
    .B(_128_),
    .Y(_131_)
  );
  NOR _269_ (
    .A(_131_),
    .B(_126_),
    .Y(_132_)
  );
  NAND _270_ (
    .A(_132_),
    .B(_121_),
    .Y(_133_)
  );
  NAND _271_ (
    .A(_129_),
    .B(data_in[1]),
    .Y(_134_)
  );
  NAND _272_ (
    .A(_118_),
    .B(data_in[2]),
    .Y(_135_)
  );
  NAND _273_ (
    .A(_135_),
    .B(_134_),
    .Y(_136_)
  );
  NAND _274_ (
    .A(_127_),
    .B(data_in[3]),
    .Y(_137_)
  );
  NAND _275_ (
    .A(_137_),
    .B(select[2]),
    .Y(_138_)
  );
  NOR _276_ (
    .A(_138_),
    .B(_136_),
    .Y(_139_)
  );
  NOR _277_ (
    .A(_139_),
    .B(_157_),
    .Y(_140_)
  );
  NAND _278_ (
    .A(_140_),
    .B(_133_),
    .Y(_141_)
  );
  NOT _279_ (
    .A(_159_),
    .Y(_142_)
  );
  NAND _280_ (
    .A(data_in[0]),
    .B(valid),
    .Y(_143_)
  );
  NOR _281_ (
    .A(_143_),
    .B(_142_),
    .Y(_144_)
  );
  NOR _282_ (
    .A(_119_),
    .B(select[2]),
    .Y(_145_)
  );
  NAND _283_ (
    .A(_158_),
    .B(_157_),
    .Y(_146_)
  );
  NOR _284_ (
    .A(_146_),
    .B(_145_),
    .Y(_147_)
  );
  NOR _285_ (
    .A(_147_),
    .B(_144_),
    .Y(_148_)
  );
  NAND _286_ (
    .A(_148_),
    .B(_141_),
    .Y(_002_)
  );
  NOT _287_ (
    .A(_143_),
    .Y(_001_[0])
  );
  NOT _288_ (
    .A(data_in[1]),
    .Y(_149_)
  );
  NOR _289_ (
    .A(_149_),
    .B(_157_),
    .Y(_001_[1])
  );
  NOT _290_ (
    .A(data_in[2]),
    .Y(_150_)
  );
  NAND _291_ (
    .A(_150_),
    .B(valid),
    .Y(_001_[2])
  );
  NOT _292_ (
    .A(data_in[3]),
    .Y(_151_)
  );
  NAND _293_ (
    .A(_151_),
    .B(valid),
    .Y(_001_[3])
  );
  NAND _294_ (
    .A(_122_),
    .B(valid),
    .Y(_001_[4])
  );
  NOT _295_ (
    .A(data_in[5]),
    .Y(_152_)
  );
  NAND _296_ (
    .A(_152_),
    .B(valid),
    .Y(_001_[5])
  );
  NOR _297_ (
    .A(_117_),
    .B(_157_),
    .Y(_001_[6])
  );
  NOT _298_ (
    .A(data_in[7]),
    .Y(_153_)
  );
  NAND _299_ (
    .A(_153_),
    .B(valid),
    .Y(_001_[7])
  );
  NOT _300_ (
    .A(_129_),
    .Y(_154_)
  );
  NAND _301_ (
    .A(_154_),
    .B(_119_),
    .Y(_003_[1])
  );
  NOR _302_ (
    .A(_124_),
    .B(select[2]),
    .Y(_155_)
  );
  NOR _303_ (
    .A(_155_),
    .B(_159_),
    .Y(_003_[2])
  );
  NOT _304_ (
    .A(reset_L),
    .Y(_040_)
  );
  NOT _305_ (
    .A(reset_L),
    .Y(_042_)
  );
  NOT _306_ (
    .A(reset_L),
    .Y(_044_)
  );
  NOT _307_ (
    .A(reset_L),
    .Y(_046_)
  );
  NOT _308_ (
    .A(reset_L),
    .Y(_048_)
  );
  NOT _309_ (
    .A(reset_L),
    .Y(_050_)
  );
  NOT _310_ (
    .A(reset_L),
    .Y(_052_)
  );
  NOT _311_ (
    .A(reset_L),
    .Y(_054_)
  );
  NOT _312_ (
    .A(reset_L),
    .Y(_056_)
  );
  NOT _313_ (
    .A(reset_L),
    .Y(_058_)
  );
  NOT _314_ (
    .A(reset_L),
    .Y(_059_)
  );
  NOT _315_ (
    .A(reset_L),
    .Y(_061_)
  );
  NOT _316_ (
    .A(reset_L),
    .Y(_063_)
  );
  NOT _317_ (
    .A(reset_L),
    .Y(_065_)
  );
  NOT _318_ (
    .A(reset_L),
    .Y(_066_)
  );
  NOT _319_ (
    .A(reset_L),
    .Y(_068_)
  );
  NOT _320_ (
    .A(reset_L),
    .Y(_070_)
  );
  NOT _321_ (
    .A(reset_L),
    .Y(_072_)
  );
  NOT _322_ (
    .A(reset_L),
    .Y(_073_)
  );
  NOT _323_ (
    .A(reset_L),
    .Y(_075_)
  );
  NOT _324_ (
    .A(reset_L),
    .Y(_077_)
  );
  NOT _325_ (
    .A(reset_L),
    .Y(_079_)
  );
  NOT _326_ (
    .A(reset_L),
    .Y(_081_)
  );
  NOT _327_ (
    .A(reset_L),
    .Y(_083_)
  );
  NOT _328_ (
    .A(reset_L),
    .Y(_085_)
  );
  NOT _329_ (
    .A(reset_L),
    .Y(_087_)
  );
  NOT _330_ (
    .A(reset_L),
    .Y(_089_)
  );
  NOT _331_ (
    .A(reset_L),
    .Y(_004_)
  );
  NOT _332_ (
    .A(select[0]),
    .Y(_003_[0])
  );
  NOT _333_ (
    .A(counterBC[0]),
    .Y(_156_)
  );
  NOT _334_ (
    .A(valid),
    .Y(_157_)
  );
  NAND _335_ (
    .A(select[1]),
    .B(select[2]),
    .Y(_158_)
  );
  NOR _336_ (
    .A(_158_),
    .B(_003_[0]),
    .Y(_159_)
  );
  NAND _337_ (
    .A(_159_),
    .B(_157_),
    .Y(_160_)
  );
  NOR _338_ (
    .A(_160_),
    .B(_156_),
    .Y(_161_)
  );
  NOT _339_ (
    .A(_160_),
    .Y(_162_)
  );
  NOR _340_ (
    .A(_162_),
    .B(counterBC[0]),
    .Y(_163_)
  );
  NOR _341_ (
    .A(_163_),
    .B(_161_),
    .Y(_000_[0])
  );
  NOR _342_ (
    .A(_161_),
    .B(counterBC[1]),
    .Y(_164_)
  );
  NOT _343_ (
    .A(counterBC[1]),
    .Y(_165_)
  );
  NOR _344_ (
    .A(_165_),
    .B(_156_),
    .Y(_005_)
  );
  NOT _345_ (
    .A(_005_),
    .Y(_006_)
  );
  NOR _346_ (
    .A(_006_),
    .B(_160_),
    .Y(_007_)
  );
  NOR _347_ (
    .A(_007_),
    .B(_164_),
    .Y(_000_[1])
  );
  NOT _348_ (
    .A(counterBC[2]),
    .Y(_008_)
  );
  NOT _349_ (
    .A(_007_),
    .Y(_009_)
  );
  NOR _350_ (
    .A(_009_),
    .B(_008_),
    .Y(_010_)
  );
  NOR _351_ (
    .A(_007_),
    .B(counterBC[2]),
    .Y(_011_)
  );
  NOR _352_ (
    .A(_011_),
    .B(_010_),
    .Y(_000_[2])
  );
  NOT _353_ (
    .A(counterBC[3]),
    .Y(_012_)
  );
  NOR _354_ (
    .A(_012_),
    .B(_008_),
    .Y(_013_)
  );
  NAND _355_ (
    .A(_013_),
    .B(_005_),
    .Y(_014_)
  );
  DFFSR _356_ (
    .C(clock32),
    .D(_001_[0]),
    .Q(data2sent[0]),
    .R(_040_),
    .S(1'b0)
  );
  DFFSR _357_ (
    .C(clock32),
    .D(_001_[1]),
    .Q(data2sent[1]),
    .R(_042_),
    .S(1'b0)
  );
  DFFSR _358_ (
    .C(clock32),
    .D(_001_[2]),
    .Q(data2sent[2]),
    .R(_044_),
    .S(1'b0)
  );
  DFFSR _359_ (
    .C(clock32),
    .D(_001_[3]),
    .Q(data2sent[3]),
    .R(_046_),
    .S(1'b0)
  );
  DFFSR _360_ (
    .C(clock32),
    .D(_001_[4]),
    .Q(data2sent[4]),
    .R(_048_),
    .S(1'b0)
  );
  DFFSR _361_ (
    .C(clock32),
    .D(_001_[5]),
    .Q(data2sent[5]),
    .R(_050_),
    .S(1'b0)
  );
  DFFSR _362_ (
    .C(clock32),
    .D(_001_[6]),
    .Q(data2sent[6]),
    .R(_052_),
    .S(1'b0)
  );
  DFFSR _363_ (
    .C(clock32),
    .D(_001_[7]),
    .Q(data2sent[7]),
    .R(_054_),
    .S(1'b0)
  );
  DFFSR _364_ (
    .C(clock32),
    .D(_002_),
    .Q(data_out),
    .R(_056_),
    .S(1'b0)
  );
  DFFSR _365_ (
    .C(clock32),
    .D(_000_[0]),
    .Q(counterBC[0]),
    .R(_058_),
    .S(1'b0)
  );
  DFFSR _366_ (
    .C(clock32),
    .D(_000_[1]),
    .Q(counterBC[1]),
    .R(_059_),
    .S(1'b0)
  );
  DFFSR _367_ (
    .C(clock32),
    .D(_000_[2]),
    .Q(counterBC[2]),
    .R(_061_),
    .S(1'b0)
  );
  DFFSR _368_ (
    .C(clock32),
    .D(_000_[3]),
    .Q(counterBC[3]),
    .R(_063_),
    .S(1'b0)
  );
  DFFSR _369_ (
    .C(clock32),
    .D(_000_[4]),
    .Q(counterBC[4]),
    .R(_065_),
    .S(1'b0)
  );
  DFFSR _370_ (
    .C(clock32),
    .D(_000_[5]),
    .Q(counterBC[5]),
    .R(_066_),
    .S(1'b0)
  );
  DFFSR _371_ (
    .C(clock32),
    .D(_000_[6]),
    .Q(counterBC[6]),
    .R(_068_),
    .S(1'b0)
  );
  DFFSR _372_ (
    .C(clock32),
    .D(_000_[7]),
    .Q(counterBC[7]),
    .R(_070_),
    .S(1'b0)
  );
  DFFSR _373_ (
    .C(clock32),
    .D(_000_[8]),
    .Q(counterBC[8]),
    .R(_072_),
    .S(1'b0)
  );
  DFFSR _374_ (
    .C(clock32),
    .D(_000_[9]),
    .Q(counterBC[9]),
    .R(_073_),
    .S(1'b0)
  );
  DFFSR _375_ (
    .C(clock32),
    .D(_000_[10]),
    .Q(counterBC[10]),
    .R(_075_),
    .S(1'b0)
  );
  DFFSR _376_ (
    .C(clock32),
    .D(_000_[11]),
    .Q(counterBC[11]),
    .R(_077_),
    .S(1'b0)
  );
  DFFSR _377_ (
    .C(clock32),
    .D(_000_[12]),
    .Q(counterBC[12]),
    .R(_079_),
    .S(1'b0)
  );
  DFFSR _378_ (
    .C(clock32),
    .D(_000_[13]),
    .Q(counterBC[13]),
    .R(_081_),
    .S(1'b0)
  );
  DFFSR _379_ (
    .C(clock32),
    .D(_000_[14]),
    .Q(counterBC[14]),
    .R(_083_),
    .S(1'b0)
  );
  DFFSR _380_ (
    .C(clock32),
    .D(_000_[15]),
    .Q(counterBC[15]),
    .R(_085_),
    .S(1'b0)
  );
  DFFSR _381_ (
    .C(clock32),
    .D(_003_[0]),
    .Q(select[0]),
    .R(_087_),
    .S(1'b0)
  );
  DFFSR _382_ (
    .C(clock32),
    .D(_003_[1]),
    .Q(select[1]),
    .R(_089_),
    .S(1'b0)
  );
  DFFSR _383_ (
    .C(clock32),
    .D(_003_[2]),
    .Q(select[2]),
    .R(_004_),
    .S(1'b0)
  );
endmodule
