/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 4.8.4-2ubuntu1~14.04.3 -O2 -fstack-protector -fPIC -Os) */

(* top =  1  *)
(* src = "byte_stripping.v:1" *)
module byte_stripping(data_in, valid, reset_L, clock1, clock2, clock4, lane_0, lane_1, valid0, valid1);
  (* src = "byte_stripping.v:3" *)
  input clock1;
  (* src = "byte_stripping.v:3" *)
  input clock2;
  (* src = "byte_stripping.v:3" *)
  input clock4;
  (* src = "byte_stripping.v:2" *)
  input [31:0] data_in;
  (* src = "byte_stripping.v:4" *)
  output [31:0] lane_0;
  (* src = "byte_stripping.v:4" *)
  output [31:0] lane_1;
  (* src = "byte_stripping.v:3" *)
  input reset_L;
  (* src = "byte_stripping.v:3" *)
  input valid;
  (* src = "byte_stripping.v:5" *)
  output valid0;
  (* src = "byte_stripping.v:5" *)
  output valid1;
  assign lane_0 = 32'd0;
  assign lane_1 = 32'd0;
  assign valid0 = 1'b0;
  assign valid1 = 1'b0;
endmodule
