/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 4.8.4-2ubuntu1~14.04.3 -O2 -fstack-protector -fPIC -Os) */

(* top =  1  *)
(* src = "clock.v:1" *)
module clkS(clock32, reset_L, clock4, clock2, clock1);
  (* src = "clock.v:7" *)
  wire _00_;
  (* src = "clock.v:7" *)
  wire _01_;
  (* src = "clock.v:7" *)
  wire _02_;
  (* src = "clock.v:7" *)
  wire _03_;
  (* src = "clock.v:7" *)
  wire _04_;
  (* src = "clock.v:7" *)
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  (* src = "clock.v:3" *)
  output clock1;
  (* src = "clock.v:3" *)
  output clock2;
  (* src = "clock.v:2" *)
  input clock32;
  (* src = "clock.v:3" *)
  output clock4;
  (* src = "clock.v:6" *)
  wire counter0;
  (* src = "clock.v:6" *)
  wire counter1;
  (* src = "clock.v:6" *)
  wire counter2;
  (* src = "clock.v:2" *)
  input reset_L;
  NOT _30_ (
    .A(reset_L),
    .Y(_06_)
  );
  NOT _31_ (
    .A(clock4),
    .Y(_07_)
  );
  NOR _32_ (
    .A(counter0),
    .B(counter1),
    .Y(_08_)
  );
  NAND _33_ (
    .A(_08_),
    .B(_07_),
    .Y(_09_)
  );
  NAND _34_ (
    .A(_09_),
    .B(counter2),
    .Y(_10_)
  );
  NOT _35_ (
    .A(counter2),
    .Y(_11_)
  );
  NOT _36_ (
    .A(counter1),
    .Y(_12_)
  );
  NOT _37_ (
    .A(counter0),
    .Y(_03_)
  );
  NAND _38_ (
    .A(_03_),
    .B(_12_),
    .Y(_15_)
  );
  NOR _39_ (
    .A(_15_),
    .B(clock4),
    .Y(_17_)
  );
  NAND _40_ (
    .A(_17_),
    .B(_11_),
    .Y(_19_)
  );
  NAND _41_ (
    .A(_19_),
    .B(_10_),
    .Y(_05_)
  );
  NAND _42_ (
    .A(counter0),
    .B(counter1),
    .Y(_21_)
  );
  NAND _43_ (
    .A(_21_),
    .B(_15_),
    .Y(_04_)
  );
  NOR _44_ (
    .A(_09_),
    .B(counter2),
    .Y(_22_)
  );
  NOR _45_ (
    .A(_22_),
    .B(clock1),
    .Y(_23_)
  );
  NOT _46_ (
    .A(clock1),
    .Y(_24_)
  );
  NOR _47_ (
    .A(_19_),
    .B(_24_),
    .Y(_25_)
  );
  NOR _48_ (
    .A(_25_),
    .B(_23_),
    .Y(_00_)
  );
  NAND _49_ (
    .A(_09_),
    .B(clock2),
    .Y(_26_)
  );
  NOT _50_ (
    .A(clock2),
    .Y(_27_)
  );
  NAND _51_ (
    .A(_17_),
    .B(_27_),
    .Y(_28_)
  );
  NAND _52_ (
    .A(_28_),
    .B(_26_),
    .Y(_01_)
  );
  NAND _53_ (
    .A(_15_),
    .B(clock4),
    .Y(_29_)
  );
  NAND _54_ (
    .A(_29_),
    .B(_09_),
    .Y(_02_)
  );
  NOT _55_ (
    .A(reset_L),
    .Y(_13_)
  );
  NOT _56_ (
    .A(reset_L),
    .Y(_14_)
  );
  NOT _57_ (
    .A(reset_L),
    .Y(_16_)
  );
  NOT _58_ (
    .A(reset_L),
    .Y(_18_)
  );
  NOT _59_ (
    .A(reset_L),
    .Y(_20_)
  );
  DFFSR _60_ (
    .C(clock32),
    .D(_02_),
    .Q(clock4),
    .R(_13_),
    .S(1'b0)
  );
  DFFSR _61_ (
    .C(clock32),
    .D(_01_),
    .Q(clock2),
    .R(_14_),
    .S(1'b0)
  );
  DFFSR _62_ (
    .C(clock32),
    .D(_00_),
    .Q(clock1),
    .R(_16_),
    .S(1'b0)
  );
  DFFSR _63_ (
    .C(clock32),
    .D(_03_),
    .Q(counter0),
    .R(_18_),
    .S(1'b0)
  );
  DFFSR _64_ (
    .C(clock32),
    .D(_04_),
    .Q(counter1),
    .R(_20_),
    .S(1'b0)
  );
  DFFSR _65_ (
    .C(clock32),
    .D(_05_),
    .Q(counter2),
    .R(_06_),
    .S(1'b0)
  );
endmodule
