/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 4.8.4-2ubuntu1~14.04.3 -O2 -fstack-protector -fPIC -Os) */

(* top =  1  *)
(* src = "serial_paraleloS.v:1" *)
module serial_paraleloS(data_in, clock32, clock4, reset_L, data_out, valid_out);
  (* src = "serial_paraleloS.v:10" *)
  wire _000_;
  (* src = "serial_paraleloS.v:10" *)
  wire [7:0] _001_;
  (* src = "serial_paraleloS.v:10" *)
  wire _002_;
  (* src = "serial_paraleloS.v:10" *)
  wire [1:0] _003_;
  (* src = "serial_paraleloS.v:10" *)
  wire [2:0] _004_;
  (* src = "serial_paraleloS.v:10" *)
  wire [7:0] _005_;
  (* src = "serial_paraleloS.v:10" *)
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  (* src = "serial_paraleloS.v:9" *)
  wire active;
  (* src = "serial_paraleloS.v:6" *)
  wire [7:0] bus;
  (* src = "serial_paraleloS.v:2" *)
  input clock32;
  (* src = "serial_paraleloS.v:2" *)
  input clock4;
  (* src = "serial_paraleloS.v:7" *)
  wire [2:0] counter;
  (* src = "serial_paraleloS.v:9" *)
  wire counter0;
  (* src = "serial_paraleloS.v:8" *)
  wire [1:0] counterBC;
  (* src = "serial_paraleloS.v:2" *)
  input data_in;
  (* src = "serial_paraleloS.v:3" *)
  output [7:0] data_out;
  (* src = "serial_paraleloS.v:2" *)
  input reset_L;
  (* src = "serial_paraleloS.v:4" *)
  output valid_out;
  NOT _130_ (
    .A(counter[2]),
    .Y(_087_)
  );
  NOT _131_ (
    .A(counter[0]),
    .Y(_088_)
  );
  NAND _132_ (
    .A(counter[1]),
    .B(_088_),
    .Y(_089_)
  );
  NOR _133_ (
    .A(_089_),
    .B(_087_),
    .Y(_090_)
  );
  NOR _134_ (
    .A(_090_),
    .B(bus[1]),
    .Y(_091_)
  );
  NOT _135_ (
    .A(data_in),
    .Y(_092_)
  );
  NAND _136_ (
    .A(_090_),
    .B(_092_),
    .Y(_093_)
  );
  NAND _137_ (
    .A(_093_),
    .B(reset_L),
    .Y(_094_)
  );
  NOR _138_ (
    .A(_094_),
    .B(_091_),
    .Y(_001_[1])
  );
  NOT _139_ (
    .A(counter[1]),
    .Y(_095_)
  );
  NOR _140_ (
    .A(_095_),
    .B(_088_),
    .Y(_096_)
  );
  NAND _141_ (
    .A(_096_),
    .B(counter[2]),
    .Y(_097_)
  );
  NOR _142_ (
    .A(_097_),
    .B(data_in),
    .Y(_098_)
  );
  NOT _143_ (
    .A(bus[0]),
    .Y(_099_)
  );
  NAND _144_ (
    .A(_097_),
    .B(_099_),
    .Y(_100_)
  );
  NAND _145_ (
    .A(_100_),
    .B(reset_L),
    .Y(_101_)
  );
  NOR _146_ (
    .A(_101_),
    .B(_098_),
    .Y(_001_[0])
  );
  NAND _147_ (
    .A(_095_),
    .B(counter[0]),
    .Y(_102_)
  );
  NOR _148_ (
    .A(_102_),
    .B(_087_),
    .Y(_103_)
  );
  NAND _149_ (
    .A(_103_),
    .B(data_in),
    .Y(_104_)
  );
  NOT _150_ (
    .A(reset_L),
    .Y(_105_)
  );
  NOT _151_ (
    .A(bus[2]),
    .Y(_106_)
  );
  NOR _152_ (
    .A(_103_),
    .B(_106_),
    .Y(_107_)
  );
  NOR _153_ (
    .A(_107_),
    .B(_105_),
    .Y(_108_)
  );
  NAND _154_ (
    .A(_108_),
    .B(_104_),
    .Y(_001_[2])
  );
  NOR _155_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_109_)
  );
  NAND _156_ (
    .A(_109_),
    .B(counter[2]),
    .Y(_110_)
  );
  NAND _157_ (
    .A(_110_),
    .B(bus[3]),
    .Y(_111_)
  );
  NOR _158_ (
    .A(_110_),
    .B(_092_),
    .Y(_112_)
  );
  NOR _159_ (
    .A(_112_),
    .B(_105_),
    .Y(_113_)
  );
  NAND _160_ (
    .A(_113_),
    .B(_111_),
    .Y(_001_[3])
  );
  NOT _161_ (
    .A(_096_),
    .Y(_114_)
  );
  NOR _162_ (
    .A(_114_),
    .B(counter[2]),
    .Y(_115_)
  );
  NAND _163_ (
    .A(_115_),
    .B(_092_),
    .Y(_116_)
  );
  NOT _164_ (
    .A(bus[4]),
    .Y(_117_)
  );
  NOT _165_ (
    .A(_115_),
    .Y(_118_)
  );
  NAND _166_ (
    .A(_118_),
    .B(_117_),
    .Y(_119_)
  );
  NAND _167_ (
    .A(_119_),
    .B(_116_),
    .Y(_120_)
  );
  NAND _168_ (
    .A(_120_),
    .B(reset_L),
    .Y(_001_[4])
  );
  NOR _169_ (
    .A(_089_),
    .B(counter[2]),
    .Y(_121_)
  );
  NAND _170_ (
    .A(_121_),
    .B(data_in),
    .Y(_122_)
  );
  NOT _171_ (
    .A(bus[5]),
    .Y(_123_)
  );
  NOR _172_ (
    .A(_121_),
    .B(_123_),
    .Y(_124_)
  );
  NOR _173_ (
    .A(_124_),
    .B(_105_),
    .Y(_125_)
  );
  NAND _174_ (
    .A(_125_),
    .B(_122_),
    .Y(_001_[5])
  );
  NOR _175_ (
    .A(_102_),
    .B(counter[2]),
    .Y(_126_)
  );
  NOR _176_ (
    .A(_126_),
    .B(bus[6]),
    .Y(_127_)
  );
  NAND _177_ (
    .A(_126_),
    .B(_092_),
    .Y(_128_)
  );
  NAND _178_ (
    .A(_128_),
    .B(reset_L),
    .Y(_129_)
  );
  NOR _179_ (
    .A(_129_),
    .B(_127_),
    .Y(_001_[6])
  );
  NOT _180_ (
    .A(bus[7]),
    .Y(_007_)
  );
  NAND _181_ (
    .A(_109_),
    .B(_087_),
    .Y(_008_)
  );
  NAND _182_ (
    .A(_008_),
    .B(_007_),
    .Y(_009_)
  );
  NOT _183_ (
    .A(_008_),
    .Y(_010_)
  );
  NAND _184_ (
    .A(_010_),
    .B(_092_),
    .Y(_011_)
  );
  NAND _185_ (
    .A(_011_),
    .B(_009_),
    .Y(_012_)
  );
  NAND _186_ (
    .A(_012_),
    .B(reset_L),
    .Y(_001_[7])
  );
  NOT _187_ (
    .A(counterBC[0]),
    .Y(_013_)
  );
  NOT _188_ (
    .A(counterBC[1]),
    .Y(_014_)
  );
  NAND _189_ (
    .A(_014_),
    .B(_013_),
    .Y(_015_)
  );
  NAND _190_ (
    .A(bus[4]),
    .B(bus[3]),
    .Y(_016_)
  );
  NAND _191_ (
    .A(bus[7]),
    .B(bus[5]),
    .Y(_017_)
  );
  NOR _192_ (
    .A(_017_),
    .B(_016_),
    .Y(_018_)
  );
  NOT _193_ (
    .A(bus[1]),
    .Y(_019_)
  );
  NAND _194_ (
    .A(_019_),
    .B(_099_),
    .Y(_020_)
  );
  NOT _195_ (
    .A(bus[6]),
    .Y(_021_)
  );
  NAND _196_ (
    .A(bus[2]),
    .B(_021_),
    .Y(_022_)
  );
  NOR _197_ (
    .A(_022_),
    .B(_020_),
    .Y(_023_)
  );
  NAND _198_ (
    .A(_023_),
    .B(_018_),
    .Y(_024_)
  );
  NAND _199_ (
    .A(_024_),
    .B(reset_L),
    .Y(_025_)
  );
  NOR _200_ (
    .A(_025_),
    .B(_015_),
    .Y(_000_)
  );
  NOT _201_ (
    .A(bus[3]),
    .Y(_026_)
  );
  NOR _202_ (
    .A(_117_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _203_ (
    .A(_007_),
    .B(_123_),
    .Y(_028_)
  );
  NAND _204_ (
    .A(_028_),
    .B(_027_),
    .Y(_029_)
  );
  NOR _205_ (
    .A(bus[1]),
    .B(bus[0]),
    .Y(_030_)
  );
  NOR _206_ (
    .A(_106_),
    .B(bus[6]),
    .Y(_031_)
  );
  NAND _207_ (
    .A(_031_),
    .B(_030_),
    .Y(_032_)
  );
  NOR _208_ (
    .A(_032_),
    .B(_029_),
    .Y(_033_)
  );
  NAND _209_ (
    .A(_033_),
    .B(counter0),
    .Y(_034_)
  );
  NOR _210_ (
    .A(_034_),
    .B(_013_),
    .Y(_035_)
  );
  NAND _211_ (
    .A(_034_),
    .B(_013_),
    .Y(_036_)
  );
  NAND _212_ (
    .A(_036_),
    .B(reset_L),
    .Y(_037_)
  );
  NOR _213_ (
    .A(_037_),
    .B(_035_),
    .Y(_003_[0])
  );
  NAND _214_ (
    .A(_035_),
    .B(counterBC[1]),
    .Y(_038_)
  );
  NOT _215_ (
    .A(counter0),
    .Y(_039_)
  );
  NOR _216_ (
    .A(_024_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _217_ (
    .A(_040_),
    .B(counterBC[0]),
    .Y(_041_)
  );
  NAND _218_ (
    .A(_041_),
    .B(_014_),
    .Y(_042_)
  );
  NAND _219_ (
    .A(_042_),
    .B(_038_),
    .Y(_043_)
  );
  NOR _220_ (
    .A(_043_),
    .B(_105_),
    .Y(_003_[1])
  );
  NAND _221_ (
    .A(reset_L),
    .B(counter[0]),
    .Y(_004_[0])
  );
  NOT _222_ (
    .A(_089_),
    .Y(_044_)
  );
  NOR _223_ (
    .A(_044_),
    .B(_105_),
    .Y(_045_)
  );
  NAND _224_ (
    .A(_045_),
    .B(_102_),
    .Y(_004_[1])
  );
  NAND _225_ (
    .A(_114_),
    .B(counter[2]),
    .Y(_046_)
  );
  NOR _226_ (
    .A(_115_),
    .B(_105_),
    .Y(_047_)
  );
  NAND _227_ (
    .A(_047_),
    .B(_046_),
    .Y(_004_[2])
  );
  NAND _228_ (
    .A(_039_),
    .B(reset_L),
    .Y(_048_)
  );
  NOR _229_ (
    .A(_048_),
    .B(_008_),
    .Y(_002_)
  );
  NAND _230_ (
    .A(active),
    .B(counter0),
    .Y(_049_)
  );
  NOT _231_ (
    .A(_049_),
    .Y(_050_)
  );
  NOR _232_ (
    .A(_050_),
    .B(valid_out),
    .Y(_051_)
  );
  NAND _233_ (
    .A(_015_),
    .B(active),
    .Y(_052_)
  );
  NAND _234_ (
    .A(_052_),
    .B(_040_),
    .Y(_053_)
  );
  NAND _235_ (
    .A(_053_),
    .B(reset_L),
    .Y(_054_)
  );
  NOR _236_ (
    .A(_054_),
    .B(_051_),
    .Y(_006_)
  );
  NAND _237_ (
    .A(_050_),
    .B(_099_),
    .Y(_055_)
  );
  NOT _238_ (
    .A(data_out[0]),
    .Y(_056_)
  );
  NAND _239_ (
    .A(_049_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _240_ (
    .A(_057_),
    .B(_055_),
    .Y(_058_)
  );
  NOR _241_ (
    .A(_058_),
    .B(_054_),
    .Y(_005_[0])
  );
  NAND _242_ (
    .A(_050_),
    .B(_019_),
    .Y(_059_)
  );
  NOT _243_ (
    .A(data_out[1]),
    .Y(_060_)
  );
  NAND _244_ (
    .A(_049_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _245_ (
    .A(_061_),
    .B(_059_),
    .Y(_062_)
  );
  NOR _246_ (
    .A(_062_),
    .B(_054_),
    .Y(_005_[1])
  );
  NAND _247_ (
    .A(_050_),
    .B(_106_),
    .Y(_063_)
  );
  NOT _248_ (
    .A(data_out[2]),
    .Y(_064_)
  );
  NAND _249_ (
    .A(_049_),
    .B(_064_),
    .Y(_065_)
  );
  NAND _250_ (
    .A(_065_),
    .B(_063_),
    .Y(_066_)
  );
  NOR _251_ (
    .A(_066_),
    .B(_054_),
    .Y(_005_[2])
  );
  NAND _252_ (
    .A(_050_),
    .B(_026_),
    .Y(_067_)
  );
  NOT _253_ (
    .A(data_out[3]),
    .Y(_068_)
  );
  NAND _254_ (
    .A(_049_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _255_ (
    .A(_069_),
    .B(_067_),
    .Y(_070_)
  );
  NOR _256_ (
    .A(_070_),
    .B(_054_),
    .Y(_005_[3])
  );
  NAND _257_ (
    .A(_050_),
    .B(_117_),
    .Y(_071_)
  );
  NOT _258_ (
    .A(data_out[4]),
    .Y(_072_)
  );
  NAND _259_ (
    .A(_049_),
    .B(_072_),
    .Y(_073_)
  );
  NAND _260_ (
    .A(_073_),
    .B(_071_),
    .Y(_074_)
  );
  NOR _261_ (
    .A(_074_),
    .B(_054_),
    .Y(_005_[4])
  );
  NAND _262_ (
    .A(_050_),
    .B(_123_),
    .Y(_075_)
  );
  NOT _263_ (
    .A(data_out[5]),
    .Y(_076_)
  );
  NAND _264_ (
    .A(_049_),
    .B(_076_),
    .Y(_077_)
  );
  NAND _265_ (
    .A(_077_),
    .B(_075_),
    .Y(_078_)
  );
  NOR _266_ (
    .A(_078_),
    .B(_054_),
    .Y(_005_[5])
  );
  NAND _267_ (
    .A(_050_),
    .B(_021_),
    .Y(_079_)
  );
  NOT _268_ (
    .A(data_out[6]),
    .Y(_080_)
  );
  NAND _269_ (
    .A(_049_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _270_ (
    .A(_081_),
    .B(_079_),
    .Y(_082_)
  );
  NOR _271_ (
    .A(_082_),
    .B(_054_),
    .Y(_005_[6])
  );
  NAND _272_ (
    .A(_050_),
    .B(_007_),
    .Y(_083_)
  );
  NOT _273_ (
    .A(data_out[7]),
    .Y(_084_)
  );
  NAND _274_ (
    .A(_049_),
    .B(_084_),
    .Y(_085_)
  );
  NAND _275_ (
    .A(_085_),
    .B(_083_),
    .Y(_086_)
  );
  NOR _276_ (
    .A(_086_),
    .B(_054_),
    .Y(_005_[7])
  );
  DFF _277_ (
    .C(clock32),
    .D(_005_[0]),
    .Q(data_out[0])
  );
  DFF _278_ (
    .C(clock32),
    .D(_005_[1]),
    .Q(data_out[1])
  );
  DFF _279_ (
    .C(clock32),
    .D(_005_[2]),
    .Q(data_out[2])
  );
  DFF _280_ (
    .C(clock32),
    .D(_005_[3]),
    .Q(data_out[3])
  );
  DFF _281_ (
    .C(clock32),
    .D(_005_[4]),
    .Q(data_out[4])
  );
  DFF _282_ (
    .C(clock32),
    .D(_005_[5]),
    .Q(data_out[5])
  );
  DFF _283_ (
    .C(clock32),
    .D(_005_[6]),
    .Q(data_out[6])
  );
  DFF _284_ (
    .C(clock32),
    .D(_005_[7]),
    .Q(data_out[7])
  );
  DFF _285_ (
    .C(clock32),
    .D(_006_),
    .Q(valid_out)
  );
  DFF _286_ (
    .C(clock32),
    .D(_001_[0]),
    .Q(bus[0])
  );
  DFF _287_ (
    .C(clock32),
    .D(_001_[1]),
    .Q(bus[1])
  );
  DFF _288_ (
    .C(clock32),
    .D(_001_[2]),
    .Q(bus[2])
  );
  DFF _289_ (
    .C(clock32),
    .D(_001_[3]),
    .Q(bus[3])
  );
  DFF _290_ (
    .C(clock32),
    .D(_001_[4]),
    .Q(bus[4])
  );
  DFF _291_ (
    .C(clock32),
    .D(_001_[5]),
    .Q(bus[5])
  );
  DFF _292_ (
    .C(clock32),
    .D(_001_[6]),
    .Q(bus[6])
  );
  DFF _293_ (
    .C(clock32),
    .D(_001_[7]),
    .Q(bus[7])
  );
  DFF _294_ (
    .C(clock32),
    .D(_004_[0]),
    .Q(counter[0])
  );
  DFF _295_ (
    .C(clock32),
    .D(_004_[1]),
    .Q(counter[1])
  );
  DFF _296_ (
    .C(clock32),
    .D(_004_[2]),
    .Q(counter[2])
  );
  DFF _297_ (
    .C(clock32),
    .D(_003_[0]),
    .Q(counterBC[0])
  );
  DFF _298_ (
    .C(clock32),
    .D(_003_[1]),
    .Q(counterBC[1])
  );
  DFF _299_ (
    .C(clock32),
    .D(_000_),
    .Q(active)
  );
  DFF _300_ (
    .C(clock32),
    .D(_002_),
    .Q(counter0)
  );
endmodule
